//! TOTP-3 (TF-1a) — `POST /api/admin/totp/enroll` + `/confirm`.
//!
//! Thin hyper wrappers over `aegis_control::api::totp_enrollment` (the
//! payload logic lives there, unit-tested without hyper). Both routes
//! sit BEHIND the auth middleware: a session is required, CSRF applies
//! (POST), and — the point of TOTP-2 — these are the only two endpoints
//! an enrollment-only session (`totp_verified=false`) may reach.
//!
//! The acting username comes from the middleware-injected
//! `x-aegis-actor` header (never a client-supplied value — the gate
//! strips `x-actor`).

use bytes::Bytes;
use http_body_util::Full;
use hyper::Response;

use aegis_control::api::totp_enrollment::{confirm, enroll, ConfirmOutcome};

use crate::responses::{extract_named_cookie, json_body_response, json_response};

/// Issuer label shown in the authenticator app. Uses the configured
/// `admin.environment` so `prod`/`staging` entries are distinguishable
/// (TF-1a); non URI-safe characters are dropped rather than escaped —
/// the label is cosmetic, the account identity is the username.
fn issuer_label(environment: Option<&str>) -> String {
    match environment {
        Some(env) => {
            let clean: String = env
                .chars()
                .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
                .collect();
            if clean.is_empty() {
                "Aegis".into()
            } else {
                format!("Aegis-{clean}")
            }
        }
        None => "Aegis".into(),
    }
}

fn actor_from(req: &hyper::Request<hyper::body::Incoming>) -> String {
    req.headers()
        .get("x-aegis-actor")
        .and_then(|h| h.to_str().ok())
        .unwrap_or("admin")
        .to_string()
}

/// AU-1-shaped Admin audit event for the enrollment lifecycle. Never
/// carries the secret or the code — only who/when/what stage.
fn emit_totp_audit(
    services: &aegis_control::dashboard_services::DashboardServices,
    action: &str,
    user: &str,
    ip: &str,
) {
    services.bus.emit(aegis_core::audit::AuditEvent {
        schema_version: 1,
        ts: chrono::Utc::now(),
        request_id: String::new(),
        class: aegis_core::audit::AuditClass::Admin,
        tenant_id: None,
        tier: None,
        action: action.to_string().into(),
        reason: "admin TOTP enrollment lifecycle".into(),
        client_ip: ip.to_string(),
        route_id: None,
        rule_id: None,
        risk_score: None,
        method: None,
        path: None,
        mode: None,
        fields: serde_json::json!({
            "actor": user,
            "user": user,
            "resource": "/api/admin/totp",
            "source": "dashboard",
        }),
    });
}

/// `POST /api/admin/totp/enroll` — stage a fresh secret and return the
/// scan payload (otpauth URI + inline SVG QR + manual-entry secret).
pub(crate) async fn handle_totp_enroll(
    req: hyper::Request<hyper::body::Incoming>,
    peer: std::net::SocketAddr,
    cfg: &aegis_core::config::WafConfig,
    services: &aegis_control::dashboard_services::DashboardServices,
) -> Response<Full<Bytes>> {
    let user = actor_from(&req);
    let issuer = issuer_label(cfg.admin.environment.as_deref());
    match enroll(&services.totp_store, &user, &issuer).await {
        Ok(resp) => {
            emit_totp_audit(services, "totp_enroll_started", &user, &peer.ip().to_string());
            let body = serde_json::to_string(&resp).unwrap_or_else(|_| "{}".into());
            json_body_response(200, body, "private, no-store")
        }
        Err(e) => {
            tracing::error!(error = %e, user, "totp enroll: store write failed");
            json_response(
                503,
                &serde_json::json!({
                    "ok": false,
                    "reason": "totp_store_unavailable",
                    "message": "enrollment state could not be persisted; please retry",
                }),
            )
        }
    }
}

/// `POST /api/admin/totp/confirm {code}` — verify a code generated by
/// the operator's app against the pending secret; on success the factor
/// activates and THIS session becomes fully verified (the enrollment-
/// only restriction lifts without a re-login).
pub(crate) async fn handle_totp_confirm(
    req: hyper::Request<hyper::body::Incoming>,
    peer: std::net::SocketAddr,
    services: &aegis_control::dashboard_services::DashboardServices,
) -> Response<Full<Bytes>> {
    use http_body_util::BodyExt;

    #[derive(serde::Deserialize)]
    struct ConfirmBody {
        code: String,
    }

    let user = actor_from(&req);
    // Session cookie BEFORE consuming the body — we need it to lift the
    // enrollment-only flag on success.
    let session_cookie = req
        .headers()
        .get_all(hyper::header::COOKIE)
        .iter()
        .filter_map(|h| h.to_str().ok())
        .find_map(|raw| extract_named_cookie(raw, "aegis_session"))
        .map(|s| s.to_string());

    let body_bytes = match req.into_body().collect().await {
        Ok(b) => b.to_bytes(),
        Err(e) => {
            return json_response(
                400,
                &serde_json::json!({"ok": false, "reason": "bad_request",
                                    "message": format!("body read failed: {e}")}),
            );
        }
    };
    let parsed: ConfirmBody = match serde_json::from_slice(&body_bytes) {
        Ok(p) => p,
        Err(e) => {
            return json_response(
                400,
                &serde_json::json!({"ok": false, "reason": "invalid_json",
                                    "message": format!("invalid confirm body: {e}")}),
            );
        }
    };

    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    match confirm(&services.totp_store, &user, &parsed.code, now).await {
        Ok(ConfirmOutcome::Activated) => {
            // Lift the enrollment-only restriction on the session that
            // just proved possession of the factor.
            if let Some(cookie) = session_cookie.as_deref() {
                if let Some(record) = services.auth_sessions.validate(cookie).await {
                    services.auth_sessions.mark_totp_verified(&record.id).await;
                }
            }
            emit_totp_audit(services, "totp_enroll_confirmed", &user, &peer.ip().to_string());
            json_body_response(
                200,
                serde_json::json!({
                    "ok": true,
                    "message": "TOTP activated — subsequent logins require an app code",
                })
                .to_string(),
                "private, no-store",
            )
        }
        Ok(ConfirmOutcome::InvalidCode) => json_response(
            401,
            &serde_json::json!({
                "ok": false,
                "reason": "invalid_code",
                "message": "code did not match — check the app entry and try again",
            }),
        ),
        Ok(ConfirmOutcome::NoPendingEnrollment) => json_response(
            409,
            &serde_json::json!({
                "ok": false,
                "reason": "no_pending_enrollment",
                "message": "no pending enrollment (expired or never started) — \
                            POST /api/admin/totp/enroll again",
            }),
        ),
        Err(e) => {
            tracing::error!(error = %e, user, "totp confirm: store write failed");
            json_response(
                503,
                &serde_json::json!({
                    "ok": false,
                    "reason": "totp_store_unavailable",
                    "message": "enrollment state could not be persisted; please retry",
                }),
            )
        }
    }
}
