#!/usr/bin/env bash
# tests/hackathon/summary.sh — render the post-run report.
#
# Usage: summary.sh <run-dir>
#
# Reads the artifacts captured by run.sh and emits a single
# Markdown file on stdout. run.sh redirects this into
# <run-dir>/summary.md.

set -euo pipefail
RUN_DIR="${1:?usage: summary.sh <run-dir>}"
ART="$RUN_DIR/artifacts"

# Helpers — gracefully fall back when a metric isn't present.
jq_or_dash() {
  local file="$1" path="$2"
  [[ -f "$file" ]] || { echo "—"; return; }
  jq -r "$path // \"—\"" "$file" 2>/dev/null || echo "—"
}

ts="$(basename "$RUN_DIR" | sed 's/^run-//')"

# Pull k6 metrics. Note: --summary-export shape is
# `metrics.<name>.<stat>` directly (no `.values` wrapper); Trend
# stats are avg/min/med/max/p(90)/p(95) by default. p(99) shows
# up only when summaryTrendStats is set in options.
K6="$ART/k6-summary.json"
legit_p99=$(jq_or_dash "$K6" '.metrics.legit_p99_ms["p(99)"] | (.*100|round)/100')
legit_p95=$(jq_or_dash "$K6" '.metrics.legit_p99_ms["p(95)"] | (.*100|round)/100')
legit_med=$(jq_or_dash "$K6" '.metrics.legit_p99_ms.med     | (.*100|round)/100')
legit_avg=$(jq_or_dash "$K6" '.metrics.legit_p99_ms.avg     | (.*100|round)/100')
legit_max=$(jq_or_dash "$K6" '.metrics.legit_p99_ms.max     | (.*100|round)/100')
legit_ok=$(jq_or_dash  "$K6" '.metrics.legit_ok_rate.value  | .*10000|round|./100')
attacks_total=$(jq_or_dash    "$K6" '.metrics.attacks_total.count')
attacks_detected=$(jq_or_dash "$K6" '.metrics.attacks_detected.count')
attacks_prevented=$(jq_or_dash "$K6" '.metrics.attacks_prevented.count')
http_req_total=$(jq_or_dash   "$K6" '.metrics.http_reqs.count')
http_req_rate=$(jq_or_dash    "$K6" '.metrics.http_reqs.rate | (.*100|round)/100')

# Pull WAF stats deltas
audit_delta=0
if [[ -f "$ART/audit-before-lines.txt" && -f "$ART/audit-after-lines.txt" ]]; then
  before=$(cat "$ART/audit-before-lines.txt")
  after=$(cat "$ART/audit-after-lines.txt")
  audit_delta=$(( after - before ))
fi

cat <<MD
# Round-1 stress test — $ts

> Auto-generated by \`tests/hackathon/summary.sh\`. Reads from
> \`$RUN_DIR/artifacts/\`. Re-run \`tests/hackathon/run.sh\`
> to regenerate.

## Headline

| Metric                       | Value |
|------------------------------|-------|
| Legit p99 latency            | \`${legit_p99}\` ms |
| Legit p95 latency            | \`${legit_p95}\` ms |
| Legit median latency         | \`${legit_med}\` ms |
| Legit avg latency            | \`${legit_avg}\` ms |
| Legit max latency            | \`${legit_max}\` ms |
| Legit success rate           | \`${legit_ok}\` % |
| HTTP requests (total)        | \`${http_req_total}\` |
| HTTP throughput              | \`${http_req_rate}\` req/s |
| Attack iterations (total)    | \`${attacks_total}\` |
| Attacks **detected** (any \`x-waf-action ≠ allow\`) | \`${attacks_detected}\` |
| Attacks **prevented** (detected AND status 401/403/429) | \`${attacks_prevented}\` |
| Audit-log lines written      | \`${audit_delta}\` |

## Per-detector hits

MD

if [[ -f "$ART/attacks-after.json" ]]; then
  if jq -e '.categories // .distribution // .by_detector // empty' "$ART/attacks-after.json" >/dev/null 2>&1; then
    echo '| Detector / Category | Hits | Share |'
    echo '|---------------------|------|-------|'
    jq -r '
      (.categories // [])
      | sort_by(-.count)
      | .[]
      | "| \(.name) | \(.count) | \(.pct)% |"
    ' "$ART/attacks-after.json"
  else
    echo "_attacks-after.json present but no \`categories\` / \`distribution\` / \`by_detector\` field._"
  fi
else
  echo "_no attacks-after.json captured (WAF endpoint unreachable at end-of-run)._"
fi

cat <<MD

## Files

| Artifact | Path |
|----------|------|
| Run dir          | \`$RUN_DIR\` |
| WAF stdout/log   | \`$RUN_DIR/logs/waf.log\` |
| Upstream log     | \`$RUN_DIR/logs/upstream.log\` |
| k6 stdout/log    | \`$RUN_DIR/logs/k6.log\` |
| k6 summary JSON  | \`$ART/k6-summary.json\` |
| WAF stats before | \`$ART/waf-stats-before.json\` |
| WAF stats after  | \`$ART/waf-stats-after.json\` |
| Attacks before   | \`$ART/attacks-before.json\` |
| Attacks after    | \`$ART/attacks-after.json\` |

## Pass / Fail

MD

# Naive thresholds aligned with the laptop targets in
# plans/hackathon-stress-test.md §8. Override by editing here
# once the benchmark team confirms the official bar.
TARGET_LEGIT_P99=200
TARGET_LEGIT_OK=95
TARGET_DETECT_PCT=85

verdict=":white_check_mark: PASS"
if [[ "$legit_p99" != "—" ]]; then
  if awk "BEGIN{exit !(${legit_p99} > ${TARGET_LEGIT_P99})}"; then
    verdict=":warning: legit p99 above ${TARGET_LEGIT_P99} ms target"
  fi
fi
if [[ "$legit_ok" != "—" ]]; then
  if awk "BEGIN{exit !(${legit_ok} < ${TARGET_LEGIT_OK})}"; then
    verdict=":x: legit success rate below ${TARGET_LEGIT_OK}% target"
  fi
fi
if [[ "$attacks_total" != "—" && "$attacks_total" != "0" && "$attacks_detected" != "—" ]]; then
  detect_pct=$(awk "BEGIN{printf \"%.1f\", ${attacks_detected}/${attacks_total}*100}")
  if awk "BEGIN{exit !(${detect_pct} < ${TARGET_DETECT_PCT})}"; then
    verdict=":x: detection rate ${detect_pct}% below ${TARGET_DETECT_PCT}% target"
  fi
fi

echo "$verdict"
