#!/usr/bin/env bash
# Drain-aware LB health poller for the native nginx STREAM LB.
#
# WHY: open-source nginx `stream` has only PASSIVE health checks (max_fails on
# failed TCP connects). The WAF's "Drain this node" flips /healthz/ready → 503 but
# KEEPS the :8443 data listener open, so passive checks never notice a drained node.
# This poller does the ACTIVE HTTP health check nginx-stream can't: it polls each
# node's /healthz/ready (admin :9443) and rewrites the `include`d upstream file,
# marking drained/unhealthy nodes `down`, then graceful `nginx -s reload`.
#   drain  (readiness 503) -> server ... down   -> LB stops NEW traffic (~poll interval)
#   undrain/restart (200)  -> server ... up      -> LB rejoins the node
# In-flight requests are untouched (reload is graceful; drain doesn't kill conns).
#
#   ./drain-poller.sh --once   # render the upstream file once + exit (boot/ExecStartPre)
#   ./drain-poller.sh          # poll forever, reload nginx on state change
set -u

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PFX="$HERE/native"
CONF="$HERE/nginx-stream-native.conf"
INC="$PFX/conf.d/waf_upstream.conf"
LOG="$PFX/logs/poller.log"
INTERVAL="${DRAIN_POLL_INTERVAL:-2}"
# Use the absolute nginx binary (NOT `conda run`) so this works under systemd-user,
# where conda isn't on PATH — same approach as aegis-nginx-lb.service. Override with
# NGINX_BIN if your nginx-lb env lives elsewhere.
NGINX_BIN="${NGINX_BIN:-/home/nico/miniconda3/envs/nginx-lb/bin/nginx}"
NGINX=("$NGINX_BIN" -p "$PFX" -c "$CONF")

# node = "<data_ip:proxied_port> <admin_ip:health_port>"  (health = /healthz/ready)
NODES=(
  "10.20.0.72:8443 10.20.0.72:9443"   # waf-infra-1
  "10.20.0.21:8443 10.20.0.21:9443"   # waf-2
  "10.20.0.40:8443 10.20.0.40:9443"   # waf-3
)

render() {
  echo "# GENERATED by drain-poller.sh — do not edit. Reflects live /healthz/ready."
  echo "upstream waf_nodes {"
  local up=0
  for n in "${NODES[@]}"; do
    set -- $n; local data="$1" admin="$2"
    local code
    code="$(curl -s -m2 -o /dev/null -w '%{http_code}' "http://$admin/healthz/ready" 2>/dev/null)"
    if [ "$code" = "200" ]; then
      echo "    server $data max_fails=2 fail_timeout=5s;   # ready"
      up=$((up+1))
    else
      echo "    server $data down;   # /healthz/ready=$code (drained/unhealthy)"
    fi
  done
  echo "}"
  [ "$up" -eq 0 ] && echo "# WARNING: all nodes down/draining — LB will 502" >&2
}

write_if_changed() {   # stdin = new content; returns 0 if changed
  mkdir -p "$(dirname "$INC")" "$PFX/logs"
  local new; new="$(cat)"
  if [ -f "$INC" ] && [ "$new" = "$(cat "$INC")" ]; then return 1; fi
  printf '%s\n' "$new" > "$INC.tmp" && mv "$INC.tmp" "$INC"
  return 0
}

case "${1:-loop}" in
  --once)
    render | write_if_changed || true
    echo "wrote $INC"
    ;;
  loop)
    echo "$(date -u +%FT%TZ) drain-poller start (interval ${INTERVAL}s)" >> "$LOG"
    reload() {   # graceful reload; returns non-zero on failure
      "${NGINX[@]}" -t >>"$LOG" 2>&1 && "${NGINX[@]}" -s reload >>"$LOG" 2>&1
    }
    # Force one reload at startup so a poller restart re-syncs nginx to the current
    # upstream file even when the file itself is unchanged (e.g. a prior reload
    # failed, or nginx was restarted separately). Without this, a stale running
    # config can persist because the loop only reloads on a file DIFF.
    render | write_if_changed || true
    if reload; then echo "$(date -u +%FT%TZ) startup reload OK:" >> "$LOG"; sed 's/^/  /' "$INC" >> "$LOG"
    else echo "$(date -u +%FT%TZ) ERROR: startup nginx reload failed" >> "$LOG"; fi
    while :; do
      if render | write_if_changed; then
        if reload; then
          echo "$(date -u +%FT%TZ) upstream changed -> reloaded:" >> "$LOG"
          sed 's/^/  /' "$INC" >> "$LOG"
        else
          echo "$(date -u +%FT%TZ) ERROR: nginx test/reload failed after upstream change" >> "$LOG"
        fi
      fi
      sleep "$INTERVAL"
    done
    ;;
  *) echo "usage: $0 [--once|loop]"; exit 1 ;;
esac
