apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aegis-gate.fullname" . }}
  labels:
    {{- include "aegis-gate.labels" . | nindent 4 }}
data:
  waf.yaml: |
{{- if .Values.config.raw }}
{{ .Values.config.raw | indent 4 }}
{{- else }}
{{ include "aegis-gate.generatedConfig" . | indent 4 }}
{{- end }}
