//! tonic gRPC service implementation for `AegisInfer`.

use std::sync::Arc;

use tonic::{Request, Response, Status};

use crate::batch::BatchService;
use crate::features::{extract_features, NUM_FEATURES};
use crate::stats::Stats;

// Types generated by tonic-build from proto/aegis_infer.proto.
pub mod proto {
    tonic::include_proto!("aegis.infer.v1");
}

// Re-export so main.rs can wrap InferService without knowing proto internals.
pub use proto::aegis_infer_server::AegisInferServer;

use proto::{
    aegis_infer_server::AegisInfer,
    ClassifyRequest, ClassifyResponse,
    HealthRequest,   HealthResponse,
    StatsRequest,    StatsResponse,
};

// ── Service struct ────────────────────────────────────────────────────────────

/// Clone-cheap gRPC service handle.
#[derive(Clone)]
pub struct InferService {
    batch:     BatchService,
    stats:     Arc<Stats>,
    mode:      &'static str,   // "onnx" | "mock"
    workers:   u32,
    max_batch: u32,
    delay_ms:  f32,
}

impl InferService {
    pub fn new(
        batch:     BatchService,
        stats:     Arc<Stats>,
        mode:      &'static str,
        workers:   u32,
        max_batch: u32,
        delay_ms:  f32,
    ) -> Self {
        Self { batch, stats, mode, workers, max_batch, delay_ms }
    }
}

// ── AegisInfer trait implementation ──────────────────────────────────────────

#[tonic::async_trait]
impl AegisInfer for InferService {
    // ── Classify ─────────────────────────────────────────────────────────────

    async fn classify(
        &self,
        request: Request<ClassifyRequest>,
    ) -> Result<Response<ClassifyResponse>, Status> {
        let req = request.into_inner();

        // Feature extraction: prefer pre-computed features, fall back to raw string.
        let features: [f32; NUM_FEATURES] = if req.features.len() == NUM_FEATURES {
            req.features
                .try_into()
                .expect("len checked above")
        } else if !req.raw_request.is_empty() {
            extract_features(&req.raw_request)
        } else {
            return Err(Status::invalid_argument(
                "provide either `features` (len=27) or `raw_request`",
            ));
        };

        // Submit to batch accumulator and await result.
        match self.batch.classify(features).await {
            Ok(result) => {
                let resp = ClassifyResponse {
                    request_id:  req.request_id,
                    prob_attack: result.prediction.prob_attack,
                    is_attack:   result.prediction.is_attack,
                    batch_size:  result.batch_size as u32,
                    infer_us:    result.infer_us,
                    queue_ms:    result.queue_ms,
                };
                Ok(Response::new(resp))
            }
            Err(e) => Err(Status::internal(e)),
        }
    }

    // ── Health ───────────────────────────────────────────────────────────────

    async fn health(
        &self,
        _request: Request<HealthRequest>,
    ) -> Result<Response<HealthResponse>, Status> {
        Ok(Response::new(HealthResponse {
            ok:        true,
            mode:      self.mode.to_string(),
            workers:   self.workers,
            max_batch: self.max_batch,
            delay_ms:  self.delay_ms,
        }))
    }

    // ── Stats ────────────────────────────────────────────────────────────────

    async fn stats(
        &self,
        _request: Request<StatsRequest>,
    ) -> Result<Response<StatsResponse>, Status> {
        let s = &self.stats;
        Ok(Response::new(StatsResponse {
            total_requests: s.total_requests.load(std::sync::atomic::Ordering::Relaxed),
            total_batches:  s.total_batches.load(std::sync::atomic::Ordering::Relaxed),
            avg_batch_size: s.avg_batch_size(),
            avg_infer_us:   s.avg_infer_us(),
            total_attacks:  s.total_attacks.load(std::sync::atomic::Ordering::Relaxed),
            max_batch_seen: s.max_batch.load(std::sync::atomic::Ordering::Relaxed),
            uptime_secs:    s.uptime_secs(),
        }))
    }
}
