# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: aegis_infer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'aegis_infer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x65gis_infer.proto\x12\x0e\x61\x65gis.infer.v1\"L\n\x0f\x43lassifyRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\x12\x13\n\x0braw_request\x18\x03 \x01(\t\"\x86\x01\n\x10\x43lassifyResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x13\n\x0bprob_attack\x18\x02 \x01(\x02\x12\x11\n\tis_attack\x18\x03 \x01(\x08\x12\x12\n\nbatch_size\x18\x04 \x01(\r\x12\x10\n\x08infer_us\x18\x05 \x01(\r\x12\x10\n\x08queue_ms\x18\x06 \x01(\x02\"\x0f\n\rHealthRequest\"`\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x0f\n\x07workers\x18\x03 \x01(\r\x12\x11\n\tmax_batch\x18\x04 \x01(\r\x12\x10\n\x08\x64\x65lay_ms\x18\x05 \x01(\x02\"\x0e\n\x0cStatsRequest\"\xb0\x01\n\rStatsResponse\x12\x16\n\x0etotal_requests\x18\x01 \x01(\x04\x12\x15\n\rtotal_batches\x18\x02 \x01(\x04\x12\x16\n\x0e\x61vg_batch_size\x18\x03 \x01(\x01\x12\x14\n\x0c\x61vg_infer_us\x18\x04 \x01(\x01\x12\x15\n\rtotal_attacks\x18\x05 \x01(\x04\x12\x16\n\x0emax_batch_seen\x18\x06 \x01(\r\x12\x13\n\x0buptime_secs\x18\x07 \x01(\x04\x32\xea\x01\n\nAegisInfer\x12M\n\x08\x43lassify\x12\x1f.aegis.infer.v1.ClassifyRequest\x1a .aegis.infer.v1.ClassifyResponse\x12G\n\x06Health\x12\x1d.aegis.infer.v1.HealthRequest\x1a\x1e.aegis.infer.v1.HealthResponse\x12\x44\n\x05Stats\x12\x1c.aegis.infer.v1.StatsRequest\x1a\x1d.aegis.infer.v1.StatsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aegis_infer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLASSIFYREQUEST']._serialized_start=37
  _globals['_CLASSIFYREQUEST']._serialized_end=113
  _globals['_CLASSIFYRESPONSE']._serialized_start=116
  _globals['_CLASSIFYRESPONSE']._serialized_end=250
  _globals['_HEALTHREQUEST']._serialized_start=252
  _globals['_HEALTHREQUEST']._serialized_end=267
  _globals['_HEALTHRESPONSE']._serialized_start=269
  _globals['_HEALTHRESPONSE']._serialized_end=365
  _globals['_STATSREQUEST']._serialized_start=367
  _globals['_STATSREQUEST']._serialized_end=381
  _globals['_STATSRESPONSE']._serialized_start=384
  _globals['_STATSRESPONSE']._serialized_end=560
  _globals['_AEGISINFER']._serialized_start=563
  _globals['_AEGISINFER']._serialized_end=797
# @@protoc_insertion_point(module_scope)
