# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from __grpc__ import aegis_infer_pb2 as aegis__infer__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aegis_infer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AegisInferStub(object):
    """─── Service ────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.unary_unary(
                '/aegis.infer.v1.AegisInfer/Classify',
                request_serializer=aegis__infer__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=aegis__infer__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/aegis.infer.v1.AegisInfer/Health',
                request_serializer=aegis__infer__pb2.HealthRequest.SerializeToString,
                response_deserializer=aegis__infer__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/aegis.infer.v1.AegisInfer/Stats',
                request_serializer=aegis__infer__pb2.StatsRequest.SerializeToString,
                response_deserializer=aegis__infer__pb2.StatsResponse.FromString,
                _registered_method=True)


class AegisInferServicer(object):
    """─── Service ────────────────────────────────────────────────────────────────

    """

    def Classify(self, request, context):
        """Classify a single HTTP request.
        Internally the server accumulates a batch (up to delay_ms or max_batch)
        before running ONNX inference, so latency ≤ delay_ms + infer_time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check — returns server mode and worker count.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Runtime statistics — batch sizes, latency, attack counts.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AegisInferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=aegis__infer__pb2.ClassifyRequest.FromString,
                    response_serializer=aegis__infer__pb2.ClassifyResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=aegis__infer__pb2.HealthRequest.FromString,
                    response_serializer=aegis__infer__pb2.HealthResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=aegis__infer__pb2.StatsRequest.FromString,
                    response_serializer=aegis__infer__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis.infer.v1.AegisInfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis.infer.v1.AegisInfer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AegisInfer(object):
    """─── Service ────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.infer.v1.AegisInfer/Classify',
            aegis__infer__pb2.ClassifyRequest.SerializeToString,
            aegis__infer__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.infer.v1.AegisInfer/Health',
            aegis__infer__pb2.HealthRequest.SerializeToString,
            aegis__infer__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis.infer.v1.AegisInfer/Stats',
            aegis__infer__pb2.StatsRequest.SerializeToString,
            aegis__infer__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
